<?php
/**
 * Gutenverse About content.
 */
return array(
	'title'      => __( 'Gutenverse About', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-RZRJHk","verticalAlign":"center","background":{"type":"default","color":""},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"40","left":"10","right":"10","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"40","left":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
                <div class="section-wrapper" data-id="RZRJHk"><script>var topRZRJHk = {"Desktop":{"point":"0","unit":"px"}};var bottomRZRJHk = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-RZRJHk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100,"Mobile":null},"elementId":"guten-Fue21G","background":{"type":"default","image":{"Desktop":{"id":131,"image":"' . esc_url( STARTUPZY_URI ) . 'assets/img/adult-african-black-blonde-business-businessman-1629587-pxhere.com.webp"}},"position":{"Desktop":"center left","Tablet":"default","Mobile":"center center"},"size":{"Desktop":"cover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"50","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"40","bottom":"10","left":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
                <div class="wp-block-gutenverse-column guten-element guten-column guten-Fue21G animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Fue21G"><script>var topFue21G = {"Desktop":{"point":"0","unit":"px"}};var bottomFue21G = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-kKdrWZ","space":{"Desktop":{"point":"380","unit":"px"},"Mobile":{"point":"63","unit":"px"}}} -->
                <div class="guten-element guten-spacer guten-kKdrWZ"></div>
                <!-- /wp:gutenverse/spacer -->
                
                <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qIBu0C","background":{"type":"default","color":{"r":30,"g":112,"b":234,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"-40","left":"80"}},"Mobile":{"unit":"px","dimension":{"left":"20","top":"140"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"60","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","top":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
                <div class="section-wrapper" data-id="qIBu0C"><script>var topqIBu0C = {"Desktop":{"point":"0","unit":"px"}};var bottomqIBu0C = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-qIBu0C animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-vNejbR","horizontalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
                <div class="wp-block-gutenverse-column guten-element guten-column guten-vNejbR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vNejbR"><script>var topvNejbR = {"Desktop":{"point":"0","unit":"px"}};var bottomvNejbR = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-eUzvly","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Arial","value":"Arial","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"style":"italic","lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"400"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":"2"}} -->
                <div class="guten-element gutenverse-text-editor guten-eUzvly"><div class="text-content-inner"><!-- wp:paragraph -->
                <p>Don’t try to tell the client what he wants. If you want to be smart, be smart in the shower. Then get out, go to work, and serve the client.</p>
                <!-- /wp:paragraph --></div></div>
                <!-- /wp:gutenverse/text-editor -->
                
                <!-- wp:gutenverse/icon {"elementId":"guten-0Iwnvk","icon":"gtn gtn-quote-light","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"140","unit":"px"},"Mobile":{"point":"72","unit":"px"}},"iconColorTwo":{"r":255,"g":255,"b":255,"a":0.21},"iconShape":"custom","iconBorderRadius":{},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"65"},"Mobile":{"point":"118","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"unit":"%","point":"-108"},"Tablet":{"point":"-100","unit":"px"},"Mobile":{"unit":"%","point":"-41"}}} -->
                <div class="wp-block-gutenverse-icon guten-element guten-0Iwnvk guten-icon"><span class="guten-icon-wrapper custom stacked"><i class="gtn gtn-quote-light"></i></span></div>
                <!-- /wp:gutenverse/icon --></div></div></div>
                <!-- /wp:gutenverse/column --></div></section></div>
                <!-- /wp:gutenverse/section --></div></div></div>
                <!-- /wp:gutenverse/column -->
                
                <!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100,"Mobile":null},"elementId":"guten-Mkf66Z","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}}} -->
                <div class="wp-block-gutenverse-column guten-element guten-column guten-Mkf66Z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Mkf66Z"><script>var topMkf66Z = {"Desktop":{"point":"0","unit":"px"}};var bottomMkf66Z = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-8tsn0I","color":{"r":30,"g":112,"b":234,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.15"},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"uppercase"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
                <h2 class="wp-block-gutenverse-heading guten-element guten-8tsn0I animated guten-element-hide desktop-fadeInRight">About Company</h2>
                <!-- /wp:gutenverse/heading -->
                
                <!-- wp:gutenverse/heading {"elementId":"guten-yON6T7","textAlign":{"Desktop":"left","Mobile":"left"},"color":{"r":7,"g":41,"b":90,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
                <h2 class="wp-block-gutenverse-heading guten-element guten-yON6T7 animated guten-element-hide desktop-fadeInRight">We Build New Future With Best Techology</h2>
                <!-- /wp:gutenverse/heading -->
                
                <!-- wp:gutenverse/text-editor {"elementId":"guten-zr2EpN","textColor":{"r":113,"g":124,"b":144,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
                <div class="guten-element gutenverse-text-editor guten-zr2EpN animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
                <!-- /wp:paragraph --></div></div>
                <!-- /wp:gutenverse/text-editor -->
                
                <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-LehVX1"} -->
                <div class="section-wrapper" data-id="LehVX1"><script>var topLehVX1 = {"Desktop":{"point":"0","unit":"px"}};var bottomLehVX1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-LehVX1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":41.95},"elementId":"guten-8mPrNG","margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
                <div class="wp-block-gutenverse-column guten-element guten-column guten-8mPrNG animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8mPrNG"><script>var top8mPrNG = {"Desktop":{"point":"0","unit":"px"}};var bottom8mPrNG = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-3YMEeF","spaceBetween":{"Desktop":"12"},"iconColor":{"r":30,"g":112,"b":234,"a":1},"textColor":{"r":113,"g":124,"b":144,"a":1},"textIndent":{"Desktop":"15"},"textTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
                <div class="guten-element guten-icon-list guten-3YMEeF"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-L9enhA"} -->
                <div class="guten-element guten-icon-list-item guten-L9enhA"><a id="guten-L9enhA"><i class="fas fa-check-circle"></i><span class="list-text ">Free Consultations</span></a></div>
                <!-- /wp:gutenverse/icon-list-item -->
                
                <!-- wp:gutenverse/icon-list-item {"elementId":"guten-4TltBM"} -->
                <div class="guten-element guten-icon-list-item guten-4TltBM"><a id="guten-4TltBM"><i class="fas fa-check-circle"></i><span class="list-text ">Brilient Client Service</span></a></div>
                <!-- /wp:gutenverse/icon-list-item -->
                
                <!-- wp:gutenverse/icon-list-item {"elementId":"guten-VyXNSp"} -->
                <div class="guten-element guten-icon-list-item guten-VyXNSp"><a id="guten-VyXNSp"><i class="fas fa-check-circle"></i><span class="list-text ">Affordable Pricing</span></a></div>
                <!-- /wp:gutenverse/icon-list-item --></div>
                <!-- /wp:gutenverse/icon-list --></div></div></div>
                <!-- /wp:gutenverse/column -->
                
                <!-- wp:gutenverse/column {"width":{"Desktop":58.05},"elementId":"guten-tqdPHc","margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"}} -->
                <div class="wp-block-gutenverse-column guten-element guten-column guten-tqdPHc animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="tqdPHc"><script>var toptqdPHc = {"Desktop":{"point":"0","unit":"px"}};var bottomtqdPHc = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-H7juWy","spaceBetween":{"Desktop":"12"},"iconColor":{"r":30,"g":112,"b":234,"a":1},"textColor":{"r":113,"g":124,"b":144,"a":1},"textIndent":{"Desktop":"15"},"textTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
                <div class="guten-element guten-icon-list guten-H7juWy"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-6CY4iD"} -->
                <div class="guten-element guten-icon-list-item guten-6CY4iD"><a id="guten-6CY4iD"><i class="fas fa-check-circle"></i><span class="list-text ">Artifical Campaign</span></a></div>
                <!-- /wp:gutenverse/icon-list-item -->
                
                <!-- wp:gutenverse/icon-list-item {"elementId":"guten-6Spv91"} -->
                <div class="guten-element guten-icon-list-item guten-6Spv91"><a id="guten-6Spv91"><i class="fas fa-check-circle"></i><span class="list-text ">Innovative Solutions</span></a></div>
                <!-- /wp:gutenverse/icon-list-item -->
                
                <!-- wp:gutenverse/icon-list-item {"elementId":"guten-nC3xr2"} -->
                <div class="guten-element guten-icon-list-item guten-nC3xr2"><a id="guten-nC3xr2"><i class="fas fa-check-circle"></i><span class="list-text ">24/7 Support</span></a></div>
                <!-- /wp:gutenverse/icon-list-item --></div>
                <!-- /wp:gutenverse/icon-list --></div></div></div>
                <!-- /wp:gutenverse/column --></div></section></div>
                <!-- /wp:gutenverse/section -->
                
                <!-- wp:gutenverse/image {"elementId":"guten-5tk2zb","imgSrc":{"media":{"imageId":141,"sizes":{"thumbnail":{"height":104,"width":150,"url":"' . esc_url( STARTUPZY_URI ) . 'assets/img/sign-150x104.webp","orientation":"landscape"},"medium":{"height":64,"width":300,"url":"' . esc_url( STARTUPZY_URI ) . 'assets/img/sign-300x64.webp","orientation":"landscape"},"full":{"url":"' . esc_url( STARTUPZY_URI ) . 'assets/img/sign.webp","height":104,"width":487,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"%","point":"30"},"Mobile":{"unit":"%","point":"70"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"align":{"Desktop":"left"},"opacity":"0.7","animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"900"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"5"}}},"padding":{"Desktop":[]}} -->
                <div class="wp-block-gutenverse-image guten-element guten-image guten-5tk2zb animated guten-element-hide desktop-fadeInRight"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( STARTUPZY_URI ) . 'assets/img/sign.webp" height="104" width="487"/></a></div>
                <!-- /wp:gutenverse/image -->
                
                <!-- wp:gutenverse/heading {"elementId":"guten-gE2j61","type":4,"color":{"r":7,"g":41,"b":90,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1100"}} -->
                <h4 class="wp-block-gutenverse-heading guten-element guten-gE2j61 animated guten-element-hide desktop-fadeInRight">Chief Executive Officer Startup</h4>
                <!-- /wp:gutenverse/heading --></div></div></div>
                <!-- /wp:gutenverse/column --></div></section></div>
                <!-- /wp:gutenverse/section -->',
);
